language: node_js
node_js:
- '16'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-production
  on:
    branch: master
env:
  global:
  - secure: JnGcDwPOJTjkAF2Apw2ms+Ylvhxd7Iwls/OLqBe9Me31/d34QAK64J7OjU30vaEpyq3bLjm+t03fffVy163PbUwkFgZA8kE5pGi6lFHuWezTMkpoGZ1qnGd1e0G0UF+oCq1O77H2JSmZj849dnSJetkWigWej6xZu6Bwp7zNNvSDidMlA0zeOjrSJ32wGTYohZ2YVqmJl4AHMP1vWd3sjZa5HeNSO7lFLKtIZWgeh9xWJKUYCuaM6zm5Mc2ddWofyIussqk8EpTATNyIY6w4iLzCsrej86RTuPUl/CtUjJWijmbQzzz0ccwu+F1dDhWshT4CqNKq/9p912o4jh6ipBN5QeNS+c1nmheIgZOS5/vd15jUQPzjBfgLL1qjNSB8rzqAiG1nztIOBAGMa2UviEKJX+YFjiMpdnein2RIidyDq0SVCxexP2vebeItwz+wHz9Jv/0Deb+bjjntZm6d+UEaTSgY8lds+3tW6lwxUH1gvPGjhbFflyT3lnl7iszTGNYVseQoGiIKbg8zx8z0rMGe5z935Vs+CBzdeuKEA+fwT3p3QtuEZM0mr37OCZLJUscUizLzEuhU086oXORdHNsck9InAhSW8yZLyT9Fj9XxCvY8LrmYI0wVfquzzo3RN1sjVVZrgytbtU1cRg1KPTz7Nt7CQHwPXx9XfJWscdw=
  